#!/usr/bin/env bash

###############################################################################
#                                                                             #
# AnsiWeather 1.00 (c) by Frederic Cambus 2013                                #
# https://github.com/fcambus/ansiweather                                      #
#                                                                             #
# Created: 2013/08/29                                                         #
# Last Updated: 2013/10/19                                                    #
#                                                                             #
# AnsiWeather is released under the BSD 3-Clause license.                     #
# See LICENSE file for details.                                               #
#                                                                             #
###############################################################################



###[ Configuration options ]###################################################

config_file=~/.ansiweatherrc

function get_config {
	ret=""
	if [ -f $config_file ]
	then
		ret=$(grep $1 $config_file | awk -F\: '{print $2}')
	fi

	if [ "X$ret" = "X" ]
	then
		return 1
	else
		echo $ret
	fi
}

# LATITUDE
lat=$(get_config "lat" || echo "37.554476")

# LONGITUDE
lon=$(get_config "lon" || echo "126.970882")

# APIKEY
apikey=$(get_config "apikey" || echo "0")

# Location : example "Moscow,RU"
location=$(get_config "location" || echo "Moscow,RU")

# System of Units : "metric" or "imperial"
units=$(get_config "units" || echo "si")

# Display symbols : "true" or "false" (requires an Unicode capable display)
symbols=$(get_config "symbols" || echo true)


#### [ Colors and characters ]#################################################

background=$(get_config "background" || echo "\033[44m")
text=$(get_config "text" || echo "\033[36;1m")
data=$(get_config "data" || echo "\033[33;1m")
delimiter=$(get_config "delimiter" || echo "\033[35m=>")
dashes=$(get_config "dashes" || echo "\033[34m-")



###[ Unicode Symbols for icons ]###############################################

sun=$(get_config "clear-day" || echo "\033[33;1m\xe2\x98\x80")
moon=$(get_config "clear-night" || echo "\033[36m\xe2\x98\xbd")
clouds=$(get_config "cloudy" || echo "\033[37;1m\xe2\x98\x81")
rain=$(get_config "rain" || echo "\xe2\x98\x94")



###[ Fetch Weather data ]######################################################

fetch_cmd=$(get_config "fetch_cmd" || echo "curl -s ")

weather=$($fetch_cmd https://api.forecast.io/forecast/$apikey/$lat,$lon?units=$units)


###[ Process Weather data ]####################################################

city=$(echo $weather | jq -r '.timezone')
temperature=$(echo $weather | jq '.currently.temperature')
humidity=$(echo $weather | jq '.currently.humidity')
pressure=$(echo $weather | jq '.currently.pressure')
sky=$(echo $weather | jq -r '.currently.summary')
sunrise=$(echo $weather | jq '.daily.data[0].sunriseTime')
sunset=$(echo $weather | jq '.daily.data[0].sunsetTime')

###[ Set the period ]##########################################################

now=$(date +%s)
if [[ $now -ge $sunset ]] || [[ $now -le $sunrise ]]
then
	period="night"
else
	period="day"
fi



###[ Set the scale ]###########################################################

case $units in
	si)
		scale="°C"
		;;
	us)
		scale="°F"
		;;
esac



###[ Set icons ]###############################################################

if [ $symbols = true ]
then
	case $sky in
		Clear)
			if [ $period = "night" ]
			then
				icon="$moon "
			else
				icon="$sun  "
			fi
			;;
		Clouds)
			icon="$clouds  "
			;;
		Rain)
			icon="$rain  "
			;;
	esac
fi



###[ Display current Weather ]#################################################

echo -e "$background$text Current weather in $city $delimiter$data $temperature $scale $icon$dashes$text Humidity $delimiter$data $humidity % $dashes$text Pressure $delimiter$data $pressure hPa \033[0m"
